#!/bin/bash

echo "-- Compiling..."

message=`java -cp bin:lib/antlr-4.4-complete.jar wacc.visitor.Visitor $1 < $1`

ecode=$?

if [ $ecode != 0 ]
then
  echo "Errors detected during compilation! Exit code $ecode returned."
  echo "$message"
else
  echo "-- Finished"
fi

exit $ecode
